accounts/urls.py
from django.urls import path
from .views import login_view, register_view, log_out

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', log_out, name="logout"),
    path('register/', register_view, name="register"),
]

orders/urls.py
from django.urls import path
from .views import order_update

app_name = 'orders'

urlpatterns = [
    path('update/', order_update, name='order-update'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, cart_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_view, name='home'),
    path('cart/', cart_view, name='cart'),
    path('order/', include('orders.urls')),
    path('account/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path('customer/', include('customers.urls')),
    path('about/', about_view, name='about'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

customers/forms.py
from .models import Customer
from django import forms

class CustomerForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your name'
            }
        )
    )

    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your phone'
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your email'
            }
        )
    )


    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('products:products'))
        else:
            messages.warning(request,'Username or password is incorrect')
    context = {}
    return render(request, 'accounts/login.html', context)


def register_view(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)

def log_out(request):
    logout(request)
    return redirect(reverse('accounts:login'))

accounts/templates/accounts/login.html
{% extends "base.html" %} {% block content %}
<div class="row d-flex justify-content-center">
  <div class="col-lg-4 border p-3 rounded shadow-sm">
    <h1 class="text-center">Login</h1>
    <form action="" method="POST">
      {% csrf_token %}
      
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">
          <strong>{{ message|escape }}</strong>
        </div>
        {% endfor %}
      {% endif %}
      <div class="mb-3">
        <label for="username">Username</label>
        <input id="username" type="text" class="form-control" name="username" />
      </div>
      <div class="mb-3">
        <label for="password">Password</label>
        <input id="password" type="password" class="form-control" name="password" />
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary mb-2">Login</button>
        <p><a class="link-secondary text-decoration-none" href="{% url 'accounts:register' %}">Don't have a account? Register now</a></p>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %} {% block content %}
<div class="row d-flex justify-content-center">
  <div class="col-lg-4 border p-3 rounded shadow-sm">
    <h1 class="text-center">Register</h1>
    <form action="" method="POST">
      {% csrf_token %}
      
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
          
        {% endfor %}
        
      {% endif %}
        
      <div class="mb-3">
        <label for="id_username">Username</label>
        {{ form.username }}
      </div>
      <div class="mb-3">
        <label for="id_email">Email</label>
        {{ form.email }}
      </div>
      <div class="mb-3">
        <label for="id_password1">Password</label>
        {{ form.password1 }}
      </div>
      <div class="mb-3">
        <label for="id_password2">Password Confirmation</label>
        {{ form.password2 }}
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary mb-2">Register</button>
        <p>
          <a
            class="link-secondary text-decoration-none"
            href="{% url 'accounts:login' %}"
            >Already have a account? Login now</a
          >
        </p>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  let inputs = document.getElementsByTagName("input");
  for (let i in inputs) {
    let input = inputs[i];
    input.className += "form-control";
  }
</script>
{% endblock content %}