accounts/urls.py
from django.urls import path
from .views import login_view, register_view, log_out

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', log_out, name="logout"),
    path('register/', register_view, name="register"),
]

customers/urls.py
from django.urls import path
from .views import profile_view, orders_view

app_name = 'customers'

urlpatterns = [
    path('',  profile_view, name='profile-view'),
    path('orders/',  orders_view, name='orders-view'),
]

orders/urls.py
from django.urls import path
from .views import order_update

app_name = 'orders'

urlpatterns = [
    path('update/', order_update, name='order-update'),
]

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    #admin
    path('', products, name='products'),
    path('create/', product_create, name='product-create'),
    path('<int:pk>/', product_detail, name='product-detail'),
    path('featured/<int:pk>/', product_switch_featured, name='product-switch-featured'),

    #user
    path('all/', all_products, name='all-products'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, cart_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_view, name='home'),
    path('cart/', cart_view, name='cart'),
    path('order/', include('orders.urls')),
    path('account/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path('customer/', include('customers.urls')),
    path('about/', about_view, name='about'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}

{% block content %}
    <h1>About</h1>
    <p>This is about page</p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% firstof title "Page title" %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      let user = '{{ request.user }}';

      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
    </script>
  </body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}

 {% block content %}
    <table class="table table-bordered">
        <thread>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thread>
        <tbody>
            {% for item in cartItems %}
                <tr>
                    <td>{{ item.product.title }}</td>
                    <td>{{ item.product.price }}</td>
                    <td><input data-product="{{ item.product.id }}" class="quantity-input" type="number" min="0" max="100" value="{{ item.quantity }}"></td>
                    <td>{{ item.get_total }}</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
    <div class="text-end">
        <span class="fw-bold">Amount:{{ amount }}</span>
    </div>

    <script type="text/javascript">
        let inputQuantity = document.getElementsByClassName('quantity-input');
        for(let input of inputQuantity){
            let currentQuantity = parseInt(input.value);
            input.onchange = () => {
                productId = input.dataset.product;
                if(parseInt(input.value) < currentQuantity){
                    updateOrderUser(productId,'remove')
                }else{
                    updateOrderUser(productId,'add')
                }
            }
        }

        function updateOrderUser(productId, action) {
            console.log(user, 'sending data...')
            console.log(productId, action)

            let url = '/order/update/'

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({ 'productId': productId, 'action': action })
            })

                .then((response) => {
                    return response.json()
                })

                .then((data) => {
                    console.log('data:'+data)
                    location.reload()
                })
        }
    </script>

 {% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home</h1>
    <p>This is home page</p>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Try Django</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:all-products' %}">Products</a>
          </li>
          
          {% if not request.user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customers:profile-view' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customers:orders-view' %}">Orders</a>
            </li>
          {% endif %}
            
        </ul>
        <span class="navbar-text me-3"><a href="{% url 'cart' %}">Cart:{{ cartTotal }}</a></span>
        <span class="navbar-text">
          {% if request.user.is_anonymous %}
            <a class="text-decoration-none ms-3" href="{% url 'accounts:login' %}">Login</a>
          {% else %}
            Hello, {{ request.user }}
            <a class="text-decoration-none ms-3" href="{% url 'accounts:logout' %}">Logout</a>
          {% endif %}
        </span>
      </div>
    </div>
  </nav>