orders/urls.py
from django.urls import path
from .views import order_update

app_name = 'orders'

urlpatterns = [
    path('update/', order_update, name='order-update'),
]

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    #admin
    path('', products, name='products'),
    path('create/', product_create, name='product-create'),
    path('<int:pk>/', product_detail, name='product-detail'),
    path('featured/<int:pk>/', product_switch_featured, name='product-switch-featured'),

    #user
    path('all/', all_products, name='all-products'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, cart_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_view, name='home'),
    path('cart/', cart_view, name='cart'),
    path('order/', include('orders.urls')),
    path('account/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path('customer/', include('customers.urls')),
    path('about/', about_view, name='about'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=255, unique=True)
    price = models.DecimalField(decimal_places=2, max_digits=100000000)
    description = models.TextField(max_length=1000)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"pk": self.pk})

    def get_switch_featured(self):
        return reverse("products:product-switch-featured", kwargs={"pk": self.pk})

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your title'
            }
        )
    )

    price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your description'
            }
        )
    )

    featured = forms.BooleanField(required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
                'placeholder': 'Your description'
            }
        )
    )

    class Meta:
        model = Product
        fields = '__all__'

    # def clean_title(self, *args, **kwargs):
    #     title = self.cleaned_data.get('title')
    #     print('title:', title)
    #     if not 'abc' in title:
    #         raise forms.ValidationError("Title is not a valid")
    #     return title

products/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from .forms import ProductForm
from .models import Product
from .filters import ProductFilter
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_user

# Create your views here.


@login_required(login_url='accounts:login')
@allowed_user(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all()

    productFilter = ProductFilter(request.GET, queryset=products)
    products = productFilter.qs

    context = {'title': 'Products', 'products': products,
               'productFilter': productFilter}
    return render(request, 'products/products.html', context)


@login_required(login_url='accounts:login')
def product_create(request):
    form = ProductForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('products:products'))
    context = {'title': 'Create Product', 'form': form}
    return render(request, 'products/product_create.html', context)


@login_required(login_url='accounts:login')
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('products:products'))
    context = {'title': product.title.capitalize(), 'form': form}
    return render(request, 'products/product_create.html', context)


@login_required(login_url='accounts:login')
def product_switch_featured(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.featured = not product.featured
    product.save(update_fields=["featured"])
    return redirect(reverse('products:products'))


def all_products(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'products/index.html', context)

products/templates/products/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <h1>Index</h1>
    <div class="d-flex flex-wrap">
        {% for product in products %}
            <div class="card ms-2 mb-4" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ product.price }}</h6>
                <p class="card-text">{{ product.description }}</p>
                <button data-product="{{ product.id}}" data-action="add" class="btn btn-primary update-cart">Add to cart</button>
                </div>
            </div>
        {% endfor %}
    </div>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

{% endblock content %}

products/templates/products/product_create.html
{% extends "base.html" %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Save" />
</form>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ product.title }}</h1>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex mb-2 flex-row-reverse justify-content-between">
  <div class="option">
    <a class="btn btn-primary" href="{% url 'products:product-create' %}">Add Product</a>
  </div>
  <form class="row row-cols-lg-auto" method="GET">
    <div class="col-12">
      {{ productFilter.form }}
    </div>
    <div class="col-12">
      <button class="btn btn-primary" type="submit">Search</button>
    </div>
  </form>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Price</th>
      <th>Featured</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
      <tr>
        <td>{{ product.id }}</td>
        <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
        <td>{{ product.price }} $</td>
        <td>
          <div class="form-check form-switch">
            {% if product.featured %}
              <div class="form-check form-switch">
                  <input onClick="window.location.href='{{ product.get_switch_featured }}'" class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                  <label class="form-check-label" for="flexSwitchCheckChecked" >On</label>
              </div>
            {% else %}
              <div class="form-check form-switch">
                <input onClick="window.location.href='{{ product.get_switch_featured }}'" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                <label class="form-check-label" for="flexSwitchCheckDefault">Off</label>
              </div>
            {% endif %}
          </div>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}